<?php

namespace App;

use App\Model;
use App\Zan;
use App\User;
use Illuminate\Database\Eloquent\Builder;


class Post extends Model
{

//    protected $guarded=[];//不可以注入的字段
//    protected $fillable=['title','content'];//可以注入的数据
    /**
     * 关联用户
     */
     public function user()
     {
         return $this->belongsTo(\App\User::class);
     }

     /**
      * 一对多
      * 评论模型
      */
     public function comments()
     {
         return $this->hasMany('App\Comment')->orderBy('created_at','desc');
     }

     /**
      * 赞与用户关联
      */
     public  function zan($user_id)
     {
         return $this->hasOne(\App\Zan::class)->where('user_id',$user_id);
     }

    /**
     * 赞数量
     */
     public function zans(){
         return $this->hasMany(\App\Zan::class);
     }

    /**
     * 属于某个作者的文章
     * @param Builder $query
     * @param $user_id
     * @return Builder
     */
     public function scopeAuthorBy(Builder $query,$user_id){
         return $query->where('user_id',$user_id);
     }

     public function postTopic(){
         return $this->hasMany(\App\PostTopic::class,'post_id','id');
     }

     /**
      * 不属于某个专题的文章
      */
     public function scopeTopicNotBy(Builder $query,$topic_id){
         return $query->doesntHave('postTopic','and',function ($q) use($topic_id){
             $q->where('topic_id',$topic_id);
         });
     }

     /**
      * 全局scope
      */
     protected static function boot()
     {
         parent::boot(); // TODO: Change the autogenerated stub
         static::addGlobalScope('avaiable',function (Builder $builder){
            $builder->whereIn('status',[1]);
         });
     }
}
